 <div class="row">
	<div class="col s12 m6 offset-m3 l6 offset-l3">
		<div class="card">
			<div class="card-image">
				<img src="http://materializecss.com/images/sample-1.jpg">
				<span class="card-title">Bienvenido</span>
			</div>
			<div class="card-content">
				<p>Hacer tu vida más fácil es nuestra meta, ver a tu familia feliz, nuestra recompensa.</p>
			</div>
			<div class="card-action">
				<a href="<?php echo $this->basePath() . '/auth/logout' ?>">Salir</a>
			</div>
			
		</div>
	</div>
</div>

<!--<div class="fixed-action-btn horizontal click-to-toggle">
	<a class="btn-floating btn-large red">
		<i class="material-icons">menu</i>
	</a>
    <ul>
      <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
      <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
      <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
    </ul>
</div>-->