<!DOCTYPE html>
<html lang="en">

    <head>
    <style>
        .block_br {
    background: #2E9AFE none repeat scroll 0 0;
}

   /* hr { 
   border-top: 2px solid #03a9f4; 
   border-bottom: 2px solid #8cb400; 
   border-left:none; 
   border-right:none; 
   height: 6px; 
 } */
    </style>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Stylesheet -->
       <!-- <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100,400italic,500,300italic,500italic,700,700italic' rel='stylesheet' type='text/css'>
        <link href="css/materialize.min.css" rel="stylesheet">
        <link href="css/slider.css" rel="stylesheet" type="text/css">
        <link href="css/animate.css" rel="stylesheet" type="text/css">
        <link href="css/ionicons.min.css" rel="stylesheet" type="text/css">
        <link href="css/style.css" rel="stylesheet" type="text/css">
        <script src="js/modernizr.custom.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js"></script>

         Favicons -->
        <!-- <link rel="apple-touch-icon-precomposed" sizes="57x57" href="img/icons/favicons/57px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/icons/favicons/114px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/icons/favicons/72px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/icons/favicons/114px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="60x60" href="img/icons/favicons/60px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="120x120" href="img/icons/favicons/120px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="76x76" href="img/icons/favicons/76px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href="img/icons/favicons/152px.png" />
        <link rel="icon" type="image/x-icon" href="img/icons/favicons/32px.png" />
        <link rel="icon" type="image/png" href="img/icons/favicons/196px.png" sizes="196x196" />
        <link rel="icon" type="image/png" href="img/icons/favicons/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/png" href="img/icons/favicons/32px.png" sizes="32x32" />
        <link rel="icon" type="image/png" href="img/icons/favicons/16px.png" sizes="16x16" />
        <link rel="icon" type="image/png" href="img/icons/favicons/favicon-128.png" sizes="128x128" />-->

     <link href="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.css'); ?>" rel="stylesheet" type="text/css" media="screen" >

     <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.js'); ?>"></script>
     <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/localization/validettaLang-es-ES.js'); ?>"></script>
        <meta name="application-name" content="Volkan"/>

        <!-- Title -->
        <title>Recupera by Pegalinas</title> 

    </head>

    <body>
    <br>
    <br><br>
    <br>

		<section id="faqs" class="faqs-section sec-padded-1x z-depth-1">
            <div class="container">
                <div class="row">
                    
                    <div class="col s12 m12 l12">
                        <div class="center-heading">
                            <h3 class="black-text">Preguntas más frecuentes</h3>               
                        </div>
                        <ul class="collapsible z-depth-2" data-collapsible="accordion">
                            <li>
                                <div class="collapsible-header active"><i class="ion-android-more-vertical"></i>¿QUÉ ES RECUPERA?</div>
                                <div class="collapsible-body"><p>Es un servicio online que te permitirá recuperar los objetos que hayas perdido de una forma ágil y sin complicaciones. Así de fácil.
                                  Con nuestra tecnología, la colaboración y disposición de la gente como tú, se pudo hacer posible en solo 3 pasos:<br>

                                  1.- Adquiere tus Pegalinas Recupera con Código QR<br>
                                  2.- Identifica tus objetos<br>
                                  3.- Recupéralos<br>
	                              </p></div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>PARA RECUPERAR MIS OBJETOS PERDIDOS. ¿QUÉ TENGO QUE HACER?</div>
                                <div class="collapsible-body"><p>Lo primero, es crear tu cuenta en nuestra plataforma WWW.RECUPERA.NET. Es muy sencillo. Solo tendrás que hacer clic en el menú superior del home “REGISTRO” y llenar un pequeño formulario con datos de contacto básicos.<br>

                                      - Nombre Completo (Nombre y apellidos)<br>
                                      - Correo electrónico<br>
                                      - Teléfono<br>
                                      - Contraseña (la que tú decidas)<br>
                                      -PIN para recoger artículos<br><br>

                                      El PIN sirve cuando un objeto es perdido por ejemplo en un colegio o gimnasio, y al ir a recoger el artículo el sistema pide dicho PIN para validar que se le está devolviendo al verdadero dueño.<br>

                                      A continuación, tendrás que aceptar nuestra política de privacidad y términos de uso haciendo clic en la casilla correspondiente.
                                      </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Y DESPUÉS?</div>
                                <div class="collapsible-body"><p>Más fácil aún. Solo tendrás que hacer clic en “Acceso” en el menú superior, identificarte con tu email y tu contraseña y podrás acceder a tu cuenta, desde donde podrás gestionar tus etiquetas codificadas, tus objetos y recuperar los que hayas perdido en cuanto éstas etiquetas hayan sido escaneadas por un tercero.</p></div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Y SI NO RECUERDO MI CONTRASEÑA?</div>
                                <div class="collapsible-body"><p>No te preocupes, también puedes recuperarla :) Solo tendrás que hacer clic en “¿Olvidaste tu contraseña?” indicarnos la dirección de email con la que te registraste en WWW.RECUPERA.NET y te enviaremos un enlace vía email desde el que podrás cambiar la contraseña por una nueva y acceder a tu cuenta de nuevo.</p></div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿CÓMO RECUPERO MIS OBJETOS PERDIDOS?</div>
                                <div class="collapsible-body"><p>Es muy sencillo.<br>

                                    1.- En primer lugar, tienes que adquirir las Pegalinas RECUPERA e identificar con ellas todas tus pertenencias. Todo lo que tenga valor para ti, debería tener su propia etiqueta con un código único RECUPERA para que puedas recuperarlo si lo pierdes.<br>
                                    2.- Si pierdes un objeto etiquetado será fácil que alguien te lo devuelva a través de nuestra plataforma online. Bien sea a través de WWW.RECUPERA.NET o bien utilizando nuestra app para dispositivos móviles RECUPERA.<br>
                                    3.- RECUPERA servirá como punto de encuentro para que quien haya localizado el objeto perdido pueda ponerse en contacto con el propietario de forma anónima: a través de una alerta móvil o, siempre que quien haya encontrado el bien lo acepte, a través de unos mínimos datos personales que faciliten la entrega.<br>

                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>YA HE ETIQUETADO MI ARTÍCULO, PERO ¿CÓMO SABE EL SISTEMA QUE ESE BIEN ES MÍO?</div>
                                <div class="collapsible-body"><p>
                                	A través de los códigos QR RECUPERA. Cada código es único e irrepetible y se asigna de forma individual a cada objeto.
                                    Una vez hayas adquirido tus Pegalinas, deberás de entrar en la sección “Mis artículos” de tu cuenta RECUPERA y podrás vincular cada código al objeto que elijas.<br>

                                    Para facilitar la recuperación deberás de agregar algunos datos sobre cada uno de tus artículos:<br>

                                    - Una o dos fotografías <br>
                                    - Nombre <br>
                                    - Categoría<br>
                                    - Marca<br>
                                    - Color<br>
                                    - Modelo<br>
                                    - Descripción breve <br>
                                    - Si lo deseas, un monto de recompensa para motivar la devolución<br>

                                    Estos datos quedarán vinculados a través de tu cuenta a tu artículo y al código QR único de la Pegalina RECUPERA correspondiente.
                                    De esta manera, una persona que escanee el código a través de su teléfono móvil o acceda a la plataforma web, podrá enviar una alerta a su propietario e iniciar el proceso de devolución/recuperación.

                                </p>
                                </div>
                            </li>                            
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>PARA DEVOLVER UN OBJETO QUE HE ENCONTRADO, ¿ES NECESARIO QUE LA PERSONA QUE LO ENCUENTRE ESTÉ REGISTRADA EN RECUPERA.NET?</div>
                                <div class="collapsible-body"><p>
                                No es necesario. Basta con que esa persona haya encontrado tu artículo y quiera devolvértelo. La etiqueta tiene un código único que podrá introducir en la página web o un código bidimensional Q.R. (Respuesta Rápida), que podrá escanear desde su teléfono para contactarte directamente, ya sea a través del lector de códigos QR de nuestra App o vía cualquier lector de códigos disponibles en las tiendas de aplicaciones. En cada Pegalina Recupera viene una leyenda que dice: Captura /Escanea para devolver.
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿CON QUÉ TIPO DE TELEFONO SE PUEDEN ESCANEAR LAS PEGALINAS?</div>
                                <div class="collapsible-body"><p>
                                Con cualquier tipo de Smartphone que cuente con una cámara, conexión a internet y cualquier App gratuita lectora de códigos QR o con el mismo lector que viene en la App de Recupera.
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿CÓMO REACCIONAN LAS PERSONAS HOY EN DIA CUANDO VEN UN CÓDIGO QR?</div>
                                <div class="collapsible-body"><p>
                                Cada vez es más común ver códigos QR en anuncios, documentos, etc. y las personas también están más familiarizadas más con ellos y su funcionamiento.
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿PUEDO MODIFICAR LOS DATOS DE MI CUENTA EN RECUPERA?</div>
                                <div class="collapsible-body"><p>
                               Si. Desde tu Perfil de usuario podrás cambiar tus datos personales y datos de contacto 
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿PARA QUÉ NECESITAN MIS DATOS PERSONALES?</div>
                                <div class="collapsible-body"><p>
                               Se necesitan para el estricto funcionamiento del servicio de recuperación de objetos perdidos. 
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿CUÁNTO CUESTA EL USO DE LA PLATAFORMA Y APP RECUPERA?</div>
                                <div class="collapsible-body"><p>
                               No tiene costo. ¡Sólo necesitas adquirir las Pegalinas RECUPERA para tener acceso a todos los beneficios!
                                    </p>
                                </div>
                            </li>

                        </ul>
                    </div> <!--Col ends -->
                </div> <!--Row ends-->
            </div> <!--Container ends -->
        </section> <!--Section ends -->


    </script>
        
        <script src="js/materialize.min.js" type="text/javascript"></script>
        <script src="js/jquery.smoothscroll.min.js" type="text/javascript"></script>
        <script src="js/typed.min.js" type="text/javascript"></script>
        <script src="js/wow.min.js" type="text/javascript"></script>
        <script src="js/waypoint.min..js" type="text/javascript"></script>
        <script src="js/jquery.counterup.min.js" type="text/javascript"></script>
        <script src="js/owl.carousel.min.js" type="text/javascript"></script>
        <script src="js/jquery.flexslider-min.js" type="text/javascript"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script src="js/classie.js" type="text/javascript"></script>
        <script src="js/config.js" type="text/javascript"></script>
       


    </body>

</html>