<br><br><br><br><br><br>
<link href="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.css'); ?>" rel="stylesheet" type="text/css" media="screen" >

<script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/localization/validettaLang-es-ES.js'); ?>"></script>

<div class="row box_anim" style="margin-top: 20px;">
	<div class="col s12 m6 offset-m3 l4 offset-l4">

		<div class="card">
			<div class="card-content">
				<form id="form_validate_mail">
					
					<div class="row">
						<div class="col s12 m12 l12 center">
    						<img class="responsive-img" src="<?php echo $this->basePath('/img/Recupera logo OK.png') ?>" alt="logo-pegalinas" />
						</div>
						<div class="col s12 m12 l12 center">
							<p class="center-align grey-text text-darken-3">Recupera, el camino m&aacute;s corto entre tus objetos perdidos y t&uacute;</p>
						</div>
					</div>

					<div class="row">
						<div class="input-field col s12 m12 l12">
							<i class="material-icons prefix">email</i>
							<input id="email" type="email" name="email_user" class="validate" data-validetta="required" data-vd-message-required="Ingresa el correo electr&oacute;nico " >
		          			<label for="email">Correo electr&oacute;nico</label>
		        		</div>
					</div>

					<div class="row">
						<div class="col s12 m12 l12">
	               			<button id="btn_validate_mail" class="waves-effect waves-light btn-large blue col s12 m12 l12">Recuperar contase&ntilde;a
	                    	</button>
						</div>
					</div>

					<!--<div class="row">
						<div class="col s6 m6 l6">
							<p class="left-align" style="font-size:25px;">
								<a href="<?php //echo $this->basePath('/users/register'); ?>">¡Reg&iacute;strate ahora!</a>
							</p>
						</div>
						<div class="col s6 m6 l6" style="font-size:25px;">
							<p class="right-align" style="font-size:25px;">
								<a href="<?php //echo $this->basePath('/auth/login'); ?>">Iniciar sesi&oacute;n</a>
							</p>
						</div>
				    </div>-->

				</form>
			</div>
		</div>

	</div>
</div>

<script>

// BasePath
var $basePath       = '<?php echo $this->basePath(); ?>';
			
// FORMULARIO contraseña sesion 
$form_validate_mail = $("#form_validate_mail");
			
$btn_validate_mail  = $('.btn_validate_mail');
            

          //  $btn_validate_mail  = $('.btn_validate_mail');

$(document).ready(function(){

		$form_validate_mail.validetta({
			bubblePosition: 'bottom',
        	bubbleGapTop: 10,
        	bubbleGapLeft: 5,
        	realTime : true,
			onValid : function( event ) {

	
				// Detenemos el evento
          		event.preventDefault();


						$.ajax({
		        			url: $basePath + '/auth/restorepassword',
		        			type: 'POST',
		        			dataType: 'json',
		        			data: $(this.form).serialize(),
		        			//alert("option");
		        		})
		        		.done(function(response) {

		        			console.log(response);
		        			console.log("success");
		        			if (response.status == 'ok') {
		        				
		        				swal({
				  					title:'Verifica tu correo electrónico',				  					
				  					imageUrl:"<?php echo $this->basePath('/img/email.png') ?>",
				  					
				  					html:'<p>¡Hemos atendido tu solicitud de cambio de contraseña, por favor verifica la bandeja de entrada dónde se te envió un liga para poder cambiarla.!</p><br><font color="red">Este token estará activo por 1 hora</font>',
				  					confirmButtonText: 'Aceptar'
				  								  					
								}).then(function () {
       							 window.location.href = $basePath + '/auth';
   								 });

		        			} else if (response.status == 'fail') {

		        				swal(
				  					'Opsss..',
				  					'¡Correo electrónico no registrado en Recupera by Pegalinas!',
				  					'error'
								);

								//grecaptcha.reset();

		        			}

			        	})
			        	.fail(function() {
			        		console.log("error");
			        	})
			        	.always(function() {
			        		console.log("complete");
			        	});

		        	}
   		});
});

    
</script>