<!DOCTYPE html>
<html lang="en">

    <head>
    


        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta property="og:image"         content="https://recupera.net/img/Recupera%20logo%20OK.png" rel="image_src"/>
        <meta property="og:type"          content="website" />
        <meta property="og:title"         content="Recupera" />
        <meta property="og:url"           content="https://recupera.net/" />  
        <meta property="og:description"   content="Your description" />

     

     <link href="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.css'); ?>" rel="stylesheet" type="text/css" media="screen" >

     <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.js'); ?>"></script>
     <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/localization/validettaLang-es-ES.js'); ?>"></script>
        <meta name="application-name" content="Volkan"/>
        <!-- Title -->
        <title>Recupera by Pegalinas</title> 



    </head>

    <body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.12&appId=1455883384716384&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<style>
        .block_br {
    background: #74C1DC none repeat scroll 0 0;
}

  /*  hr { 
   border-top: 2px solid #03a9f4; 
   border-bottom: 2px solid #8cb400; 
   border-left:none; 
   border-right:none; 
   height: 6px; 
 } */
    </style>

<style>
  .fb-share-button
{
transform: scale(1.5);
-ms-transform: scale(1.5);
-webkit-transform: scale(1.5);
-o-transform: scale(1.5);
-moz-transform: scale(1.5);
transform-origin: top left;
-ms-transform-origin: top left;
-webkit-transform-origin: top left;
-moz-transform-origin: top left;
-webkit-transform-origin: top left;
}

.video {
   position: relative;
   padding-bottom: 56.25%;
   overflow: hidden;
}
.video iframe

 {
    position: absolute;
    display: block;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}


  </style>

        <!-- Scroll-to-top Button -->
        <div class="scroll-to-top waves-effect waves-light trans-effect">
            <a href="#"><i class="ion-chevron-up"></i></a>
        </div><!-- Scroll-to-top Button ends -->

        <!-- Section home -->
        <section id="home" class="home-section" style="margin-top:70px">
            <div class="overlay-shad"></div>

            <div class="container">
                <div class="row btm-mrgn-0">

                    <div class="col s12 m4 l8">

                        <center>

                            <img src="img/plaqueta azul 858x159px.png" class="responsive-img" alt="plaqueta" style="margin-top:40px;" />

                            <img src="img/QR oval.png" class="responsive-img" alt="pegalina qr" style="margin-top:25px;"/>

                            <div class="row" style="margin-top:20px;">
                            
                                <div class="col s6 m6 l6">
                                    <a href="https://play.google.com/store/apps/details?id=com.pegalinas.recupera" class="right" target="_blank">
                                        <img class="responsive-img" src="<?php echo $this->basePath('/img/pets/Google Play.png') ?>" height="65" width="200" />
                                    </a>
                                </div>

                                <div class="col s6 m6 l6">
                                    <a href="https://appsto.re/i6dX8pj" class="left" target="_blank">
                                        <img class="responsive-img" src="<?php echo $this->basePath('/img/pets/Apple Store.png') ?>" height="65" width="200" />
                                    </a>
                                </div>

                            </div>
                            
                            <div class="row" style="margin-top:75px;">
                                <div class="col s12 m4 l4">
                                    <!--<div class="fb-share-button" data-href="http://www.your-domain.com/your-page.html" data-layout="button_count"></div>-->
                                    <!-- quitar<div class="fb-share-button" data-href="https://recupera.net/" data-layout="button" data-size="large" data-mobile-iframe="false"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Frecupera.net%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartir</a></div>-->

                                </div>

                                <div class="col s12 m4 l4">
                               <!-- quitar <a href="<?php echo $this->basePath("auth/indexpets"); ?>" target="_blank">
                                <img class="phone-wrapper responsive-img" src="<?php echo $this->basePath('/img/pets/huella 48px.ico') ?>" /> <font color="#D7287D">Recupera Mascotas</font>
                                </a>-->

                                <!-- <a class="waves-effect waves-light btn" href="http://localhost:8081/recuperalo/public/auth/indexpets" ><i class="material-icons left">pets</i>Macotas</a>-->
                                 </div>
                                 <!--<div class="col s12 m4 l4">
                                 <a class="waves-effect waves-light btn" href="http://localhost:8081/recuperalo/public/auth/community"><i class="material-icons left">pets</i>Comunidad</a>
                                 </div>-->

                                 
                            </div>

                        </center>

                    </div>

                    
                        
                    <div class="col s12 m8 l4">
                        <div class="android-wrapper trans-effect" style="margin-top:30px;">
                            <div class="android-inner trans-effect">
                                <div class="hero-slider">
                                    <ul class="slides">
                                        <!-- Replace 'src' attribute with the path to the screenshots  -->
                                        <li><img src="img/screens/4_Registrase.PNG" alt="Home"></li>
                                        <li><img src="img/screens/login ios.jpg" alt="Registro"></li>
                                        <li><img src="img/screens/lista ios.jpg" alt="Mis artículos"></li>
                                        <li><img src="img/screens/detalle ios.png" alt="Detalle"></li>
                                        <li><img src="img/screens/ajustes_2.JPG" alt="Ajustes"></li>
                                        <li><img src="img/screens/notificaciones ios.jpg" alt="Notificaciones"></li>
                                        <li><img src="img/screens/notifica ios.jpg" alt="Notificacion"></li>
                                        <li><img src="img/screens/mapa ios.jpg" alt="Notificacion"></li>
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                </div><!-- Row ends -->
            </div><!-- Container ends -->
        </section><!-- Section ends -->

        <!-- Section found -->
        <div class="row box_anim block_br" style="margin-top:118px;">
            <div class="col s12 m12 l12" style="margin-top:60px; margin-bottom:50px;">

                <h3 class="center-align"><font color="white">¿Encontraste un objeto ó mascota que quieres devolver?</font></h3>
            
                <p class="center" >
                    <a class="btn-link white-text btn-floating waves-light red">
                        <i class="ion-android-arrow-down"></i>
                    </a>
                    <font color="white" size="5">Ingresa aquí, el folio del art&iacute;culo que encontraste.</font>
                </p>

                <font color="white">
                <form id="form_article" method="POST" action="#" class="col s12 m8 offset-m2 l6 offset-l3">            
                    <div class="row">                
                        <div class="input-field col s12 m8 l8">
                            <input id="code_article" type="text" class="validate" name="code_article" data-validetta="required" data-vd-message-required="Ingresa el código del artículo" />
                            <label for="code_article"><h5><font color="white">Folio QR de art&iacute;culo</font></h5></label>
                        </div>

                        <div class="input-field col s12 m4 l4">
                            
                            <button class="btn-large waves-effect #d32f2f red darken-2  col s12 m12 l12">Iniciar Devolución
                                
                            </button>        
                        </div>
                    </div>
                </form>
                </font>

            </div>
        </div>

        <section style="margin-top:70px"><!-- Section -->
            
            <div class="container center">

                <div class="row">
                    <div class="col s12 l8 offset-l2">
                        <div class="center-heading">
                            <h3>Recupera</h3>
                            <!--<hr>-->
                            <p style="text-align: justify">RECUPERA es la solución al problema de extravío de artículos y da un giro moderno a las etiquetas personalizadas a través de su plataforma digital.Recupera.net y la App Pegalinas Recupera para teléfonos inteligentes, es la forma más sencilla y efectiva de evitar que tanto los niños como los adultos pierdan definitivamente sus chamarras, pants, tenis, bolsas, libros y una infinidad de artículos tanto en la escuela como en el gimnasio y prácticamente en cualquier parte. </p>
                        </div>
                    </div>
                </div>
                     
                <div class="video">
                    <!--<iframe  height="360" width="640" src="https://www.youtube.com/embed/twJ_9e0Svv4" frameborder="0" allowfullscreen></iframe>-->
                    <iframe width="360" height="640" src="https://www.youtube.com/embed/PFqr--WqFt8" frameborder="0" allowfullscreen></iframe>
                </div>

            </div><!-- Container ends -->
        </section><!-- Section ends -->

        <!-- Section overview -->
        <section id="overview" class="overview-section sec-padded-1x">
            <div class="container">
                <div class="row">
                    <div class="col s12 l8 offset-l2">
                        <div class="center-heading">
                            <h3>SOLUCIÓN INTEGRADA – COLABORACIÓN EFICIENTE</h3>
                            <!--<hr>-->
                             <p>! Te da control y pueden incluso reducir el estrés!</p>
                            <!--<span class="center-line red"></span>-->
                            <p style="text-align: justify">Las Pegalinas Recupera con código QR y la App móvil y Web RECUPERA, trabajan en conjunto para mantener un registro seguro de todos tus artículos personales que quieras registrar e identificar, permitiendo la comunicación ágil entre quien pierde y quien encuentra  un objeto. </p>
                        </div>
                    </div>
                </div>
                <div class="row center">
                    <div class="col s12 m6 l3">
                        <div class="card-panel overview-section-box wow fadeIn" data-wow-delay="0.1s">
                            <i class="ion-android-time trans-effect"></i>
                            <h3>Ahorra</h3>
                            <p style="text-align: justify">
                                Las Pegalinas son fáciles de aplicar. Te llevará poco identificar tus artículos y registrarlos.El uso de la App es muy intuitiva y acorta el tiempo entre que pierdes un objeto y que alguien te avisa que ya lo encontró. Ahorrarás dinero al no gastar en reponer lo extraviado.
                            </p>
                        </div>
                    </div><!-- Col ends -->
                    <div class="col s12 m6 l3">
                        <div class="card-panel overview-section-box wow fadeIn" data-wow-delay="0.2s">
                            <i class="ion-android-textsms trans-effect"></i>
                            <h3>Avisos</h3>
                            <p style="text-align: justify">
                                Al extraviarse algún objeto y alguien lo encuentra, escaneará el código en la etiquetas y de inmediato recibirás una notificación vía la App de RECUPERA, así como un correo electrónico, teniendo la oportunidad de comunicarte con quien lo encontró.  
                            </p>
                        </div>
                    </div><!-- Col ends -->
                    <div class="col s12 m6 l3">
                        <div class="card-panel overview-section-box wow fadeIn" data-wow-delay="0.3s">
                            <i class="ion-android-pin trans-effect"></i>
                            <h3>GPS</h3>
                            <p style="text-align: justify">
                                Cuando alguien en la escuela, gimnasio o cafetería encuentre y escanee el código que viene en la etiqueta con su Smartphone, el sistema te brindará la ubicación GPS de tu objeto extraviado, así como los demás datos de contacto para acudir a recuperarlo. 
                            </p>
                        </div>
                    </div><!-- Col ends -->
                    <div class="col s12 m6 l3">
                        <div class="card-panel overview-section-box wow fadeIn" data-wow-delay="0.4s">
                            <i class="ion-android-people trans-effect"></i>
                            <h3>app para todos</h3>
                            <p style="text-align: justify">
                                Cuantas más personas en sus distintas comunidades identifiquen sus pertenencias con las Pegalinas Recupera y cuenten con la App en sus teléfonos, se incrementa la probabilidad de ayudarlos a recuperar sus objetos olvidados o los de sus hijos.

                            </p>
                        </div>
                    </div><!-- Col ends -->
                </div><!-- Row ends -->
            </div><!-- Container ends -->
        </section><!-- Section ends -->

        <!-- Section features -->
        <section id="features" class="features-section sec-padded-1x">
            <div class="container">
                <div class="row">
                    <div class="col s12 l8 offset-l2">
                        <div class="center-heading">
                            <h3>¿CÓMO FUNCIONA LA APP MÓVIL?</h3>
                            <!--<hr>-->
                            <!--<span class="center-line red"></span>-->
                            <p>Da clic en la imagen del teléfono para que se despliegan algunas pantallas de la App con una breve explicación de su funcionamiento.</p>                            
                            <a  href="https://issuu.com/pegalinas.com/docs/instructivo_recupera_arti__culos" target="_blank"><font color="red" size="4">CÓMO FUNCIONA LA APP – PASO A PASO – RECUPERA ARTÍCULOS</font></a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m4 l4 features-section-row left">
                        <div class="features-section-box left top one">
                            <i class="ion-android-download z-depth-1 trans-effect"></i>
                            <div class="features-text ">
                                <h4 class="trans-effect">Descarga</h4>
                                <p style="text-align: justify">La aplicación RECUPERA es GRATUITA para todos los usuarios y está disponible para los sistemas IOS y Android en la tienda de Aplicaciones. Esto facilita que todos participen y ayuden a resolver el problema. Se trata de una verdadera solución colaborativa.</p>
                            </div>
                        </div><!-- Feature box ends -->
                        <div class="features-section-box left top two">
                            <i class="ion-android-contact z-depth-1 trans-effect"></i>
                            <div class="features-text ">
                                <h4 class="trans-effect">Registro</h4>
                                <p style="text-align: justify">Sólo ingresa tu nombre, correo electrónico, contraseña y un pin para recuperar tus artículos perdidos y tendrás acceso a todos los beneficios. Vive esta experiencia.</p>
                            </div>
                        </div><!-- Feature box ends -->
                        <div class="features-section-box left three">
                            <i class="ion-ios-home z-depth-1 trans-effect"></i>
                            <div class="features-text ">
                                <h4 class="trans-effect">Home</h4>
                                <p style="text-align: justify">El inicio de la App es muy amigable e intuitiva. Contiene dos botones, uno para registrarse y otro para acceder. Asimismo te ofrece una guía de usuario y en la parte inferior hay disponible un lector digital de códigos QR que te permitirán escanear cualquier código y ayudar a devolver un objeto perdido de alguien más.</p>
                            </div>
                        </div><!-- Feature box ends -->                        
                    </div><!-- Col ends -->
                    <div class="col s12 m4 l4 features-img-box wow zoomIn" data-wow-delay="0.1s">
                        <div id="img-wrapper" class="img-wrapper">
                            <div class="feature-device">
                                <img src="img/iphone-cover-ios.png" alt="" class="phone-wrapper responsive-img">
                                <!-- Replace 'src' attribute with the path to the screenshot  -->
                                <a href="#"><img class="screen responsive-img" src="img/screens/4_Registrase.PNG" alt=""></a>
                            </div>
                            <div class="feature-grid">
                                <!-- Replace 'src' attribute with the path to the screenshots  -->
                                <a href="#"><img src="img/screens/1_Descargar.PNG" data-num="one" alt="" class="img-responsive"><span>Descarga <small> La aplicación RECUPERA es GRATUITA para todos los usuarios y está disponible para los sistemas IOS y Android.</small></span></a>
                                <a href="#"><img src="img/screens/6_DatosDeRegistro.PNG" data-num="two" alt="" class="img-responsive"><span>Registrate <small>Para unirte a Recupera solo tienes que llenar un pequeño formulario.</small></span></a>
                                <a href="#"><img src="img/screens/4_Registrase.PNG" data-num="three" alt="" class="img-responsive"><span>Home <small>El home de la App es muy amigabl, intuitiva y facil de usar.</small></span></a>
                                <a href="#"><img src="img/screens/lista ios.jpg" data-num="four" alt="" class="img-responsive"><span>Mis artículos <small>Una vez que ingreses con tu usuario y contraseña podrás ver la lista de los articulos que diste de alta. </small></span></a>
                                <a href="#"><img src="img/screens/detalle ios.png" data-num="five" alt="" class="img-responsive"><span>Detalle del artículo <small>La app cuenta con una vista de detalle, la cual muestra la descripción del artículo.</small></span></a>
                                <a href="#"><img src="img/screens/ajustes_2.JPG" data-num="six" alt="" class="img-responsive"><span> Ajustes<small>En esta sección el usuario puede observar los terminos y condiciones de pegalinas recupera, perfil y acerca de.</small></span></a>
                            </div>
                        </div>
                    </div><!-- Col ends -->
                    <div class="col s12 m4 l4 features-section-row right">                     
                        <div class="features-section-box right four">
                            <i class="ion-ios-list z-depth-1 trans-effect"></i>
                            <div class="features-text ">
                                <h4 class="trans-effect">Mis artículos</h4>
                                <p style="text-align: justify">En esta vista puedes observar los artículos que diste de alta en tu cuenta, así como el estado en que se encuentran, por ejemplo: Registrado, extraviado, devuelto, prestado, etc.</p>
                            </div>
                        </div><!-- Feature box ends -->
                        <div class="features-section-box right five">
                            <i class="ion-eye z-depth-1 trans-effect"></i>
                            <div class="features-text ">
                                <h4 class="trans-effect">Detalle del artículo</h4>
                                <p style="text-align: justify">En la vista de detalles, se muestran los datos del artículo registrado: color, marca, talla, categoría, modelo y la recompensa ofrecida en caso de que cuente con alguna.</p>
                            </div>
                        </div><!-- Feature box ends -->
                        <div class="features-section-box right six">
                            <i class="ion-android-settings z-depth-1 trans-effect"></i>
                            <div class="features-text ">
                                <h4 class="trans-effect">Ajustes</h4>
                                <p style="text-align: justify">En esta sección el usuario puede observar los términos y condiciones de  Recupera, perfil acerca de y un centro de notificaciones donde podrás observar quien encuentra tus artículos así como su ubicación.</p>
                            </div>
                        </div><!-- Feature box ends -->
                    </div><!-- Col ends -->
                </div><!-- Row ends -->
            </div><!-- Container ends -->
        </section><!-- Section ends -->

        <!-- Section describe -->
        <section id="describe" class="describe-section z-depth-1">
            <div class="overlay-blue-shade"></div>
            <div class="sec-padded-1x">
                <div class="container">
                    <div class="row">
                        <div class="col s12 l8 offset-l2">
                            <div class="center-heading">
                                <h3 class="white-text">¿Eres un colegio, campamento, gimnasio o algún otro tipo de institución?</h3>
                                <a  href="https://issuu.com/pegalinas.com/docs/instructivo_web_instituciones" target="_blank"><font color="red" size="4"><b>INSTRUCTIVO PARA USUARIOS DE ESCUELAS ZONA RECUPERA</b></font></a>
                                <!--<hr>-->
                                <p class="white-text" style="text-align: justify">RECUPERA te ayuda a reducir de forma importante la problemática de objetos extraviados en tu institución y por lo tanto, a controlar y administrar mejor el área. Es muy fácil con nuestra plataforma gratuita de comunicación y administración de inventario. Es ideal tanto para los objetos perdidos que encuentres, como para aquellos que sean prestados a tus alumnos, asociados o clientes.</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        <div id="tab-heart" class="col s12 tab-content wow fadeIn">
                            <div class="col s12 m6 l6 center">
                                <img src="img/imagen instituciones.png" style="width:80%; height: 600px;"alt="imagen institucion" class="responsive-img">
                            </div>
                            <div class="col s12 m6 l6">
                                <h3>HEMOS CREADO UN SERVICIO QUE HACE FACIL LA DE DEVOLUCIÓN DE OBJETOS PERDIDOS</h3>
                                <p style="text-align: justify">Cuantas más personas  identifiquen sus pertenencias, se incrementa la probabilidad de recuperar sus objetos olvidados o los de sus hijos.</p> 
                                <p style="text-align: justify">Al encontrar un objeto etiquetado con Pegalina,  el responsable de Objetos Olvidados, la escaneará con su smartphone y en ese momento, se notificará automáticamente al dueño. Dicho objeto, quedará automáticamente inventariado en la cuenta que la institución tiene dentro de la Aplicación de RECUPERA.</p>
                                <p style="text-align: justify">Cuando el propietario del artículo acuda a recogerlo, se identificará con un PIN personal, para confirmar que el artículo efectivamente le pertenece y evitar que se lleve algo que no le pertenece. El PIN se valida de forma automática en la aplicación. La información de la entrega queda resguardada para una futura consulta.</p>

                                <p style="text-align: justify">Cada institución pondrá sus propias reglas sobre el tiempo que mantendrá en resguardo los objetos recuperados y lo que hará con ellos después de dicho plazo.</p>
                                <p style="text-align: justify"><b>¿Quieres reducir dramáticamente el problema de artículos extraviados en tu institución de forma gratuita? <a href="#modal1"><font color="red">Haz clic aquí</font></a></b></p>

                                
                            </div>
                        </div> 
                    </div><!-- Row ends -->
                </div><!-- Container ends -->
            </div><!-- Sec-padded ends -->
        </section><!-- Section ends -->

        <section style="margin-top:70px"><!-- Section -->
            
            <div class="container center">

                <div class="row">
                    <div class="col s12 l4 offset-l4">
                        <div class="center-heading">
                            <div class="col s12"><img src="img/Zona Recupera.png" style="width:100%; height: 100%;"alt="codigos qr" class="phone-wrapper responsive-img"></div>
                        </div>
                    </div>
                </div>
                     
                <div class="video">
                   <iframe width="360" height="640" src="https://www.youtube.com/embed/wcEXBHUPkWs" frameborder="0" allowfullscreen></iframe>
                </div>

            </div><!-- Container ends -->
        </section><!-- Section ends --><br><br><br>

        


        <!-- Section price -->
        <section id="price" class="price-section z-depth-1">
            <div class="overlay-shade"></div>
            <div class="sec-padded-1x">
                <div class="container">
                    <div class="row">
                        <div class="col s12 l12">
                            <div class="center-heading">

                                    <div class="col s12 m4 l3" style="margin-top: 40px"><img src="img/QR oval_cuadrado.png" style="width:80%; height: 80%;"alt="codigos qr" class="phone-wrapper responsive-img"></div>
                            
                                    <div class="col s12 m4 l6" style="margin-top: 80px"><h3 class="white-text">Adquiere tus Pegalinas Recupera</h3></div>
                                    
                                        <div class="col s12 m4 l3"><img src="img/tag 500x500px.png" style="width:100%; height: 100%;"alt="codigos qr" class="phone-wrapper responsive-img"></div>
                                   
                               <!-- <h3 class="white-text">Adquiere tus Pegalinas Recupera</h3>-->
                                <!--<hr>-->
                                <!--<p class="white-text" style="text-align: center">Contamos con varios tipos de Pegalinas, tanto para identificar <br>prendas como para cualquier objeto personal.</p>-->
                            </div> 
                                                
                        </div><br><br>

                         
                    </div>
                    <div class="row pricing-row center">
                        <div class="col s12 m4 l4">
                            <div class="pricing-item z-depth-2 wow fadeIn" data-wow-delay="0.1s">
                                <h3 class="pricing-title">Paquetes vinil</h3>
                                <div class="pricing-price"><span class="pricing-currency">desde $</span>135<span class="pricing-period">/ pesos</span></div>
                                <p class="pricing-sentence">Genéricas (sin nombre) y Personalizadas.</p>
                                <ul class="pricing-feature-list">
                                    <li class="pricing-feature"><i class="ion-android-checkmark-circle"></i>Ideales para identificar prácticamente cualquier objeto en escuela, guardería, oficina y en la casa. Génerica y Personalizada. Desde 24 etiquetas.</li>
                                    <li class="pricing-feature"><i class="ion-android-checkmark-circle"></i>Son de un tamaño estándar muy útil, las cuales quedáran adheridas a tu artículo por MUCHO tiempo, hasta que decidas retirarlas. Disponibles en Genéricas y Personalizadas.</li>
                                    <!--<li class="pricing-feature"><i class="ion-android-checkmark-circle"></i>Génerica y Personalizada. Desde 24 etiquetas.</li>-->                                  
                                </ul>
                                <a href="http://www.pegalinas.com/vinil/279-clasicas-recupera-generica-qr.html#/" target="_blank">
                                <button class="pricing-action waves-effect waves-light red btn tooltipped" data-position="top" data-delay="50" data-tooltip="Serás remitido a la página de pegalinas.com">adquirir</button></a>
                            </div> 
                        </div><!-- Col ends -->
                        <div class="col s12 m4 l4">
                            <div class="pricing-item pricing-item--featured z-depth-2 wow fadeIn" data-wow-delay="0.2s">
                                <div class="ribbon"><span>Mejor elección</span></div>
                                <h3 class="pricing-title">Paquetes ropa</h3>
                                <div class="pricing-price"><span class="pricing-currency">desde $</span>195<span class="pricing-period">/ pesos</span></div>
                                <p class="pricing-sentence">Genéricas (sin nombre) y Personalizadas.</p>
                                <ul class="pricing-feature-list">
                                    <li class="pricing-feature"><i class="ion-android-checkmark-circle"></i>Etiquetas termo-adhesivas, que se aplican con plancha y se vulcanizan perfectamente con la prenda para que duren mucho tiempo.</li>
                                    <li class="pricing-feature"><i class="ion-android-checkmark-circle"></i>Etiquetas Xpress, que se aplican sólo con presión y sin plancha y que duran muchísimas lavadas. Estas se pueden retirar de la prenda. Disponibles en Genéricas y Personalizadas.</li>
                                </ul>
                                <a href="http://www.pegalinas.com/ropa/274-clasicas-recupera-ropa-qr.html#/" target="_blank">
                                <button class="pricing-action waves-effect waves-light red btn tooltipped" data-position="top" data-delay="50" data-tooltip="Serás remitido a la página de pegalinas.com">adquirir</button></a>
                            </div>
                        </div><!-- Col ends -->
                        <div class="col s12 m4 l4">
                            <div class="pricing-item z-depth-2 wow fadeIn" data-wow-delay="0.3s">
                                <h3 class="pricing-title">Tag</h3>
                                <div class="pricing-price"><span class="pricing-currency">desde $</span>190<span class="pricing-period">/ pesos</span></div>
                                <p class="pricing-sentence">Genéricos (sin nombre).</p>
                                <ul class="pricing-feature-list">
                                    <li class="pricing-feature"><i class="ion-android-checkmark-circle"></i>Paquete de 2 Tags de PVC con cadena.</li>
                                    <li class="pricing-feature"><i class="ion-android-checkmark-circle"></i>Cada uno ya trae su código QR único para ser registrado.</li>
                                    <li class="pricing-feature">
                                    <i class="ion-android-checkmark-circle"></i>Ideales para identificar maletas, mochilas, portafolios, etc. 
                                    </li>
                                    <li class="pricing-feature">
                                    <i class="ion-android-checkmark-circle"></i>. Son de un tamaño estándar muy útil (12  x 4 cm).
                                    </li>
                                </ul>
                                <a href="http://www.pegalinas.com/home/275-tag-recupera-qr.html#/" target="_blank">
                                <button class="pricing-action waves-effect waves-light red btn tooltipped" data-position="top" data-delay="50" data-tooltip="Serás remitido a la página de pegalinas.com">adquirir</button></a>
                            </div>
                        </div><!-- Col ends -->
                    </div><!-- Row ends -->
                </div><!-- Container ends -->
            </div><!-- Sec-padded ends -->  
        </section><!-- Section ends -->

        <!-- Section team -->
        <!-- <section id="team" class="team-section z-depth-1">
            <div class="sec-padded-1x">
                <div class="container">
                    <div class="row">
                        <div class="col s12 l8 offset-l2">
                            <div class="center-heading">
                                <h3 class="white-text">The team</h3>
                                <span class="center-line red"></span>
                                <p class="white-text">Lorem ipsum dolor sit amet consectetur adipisicing elit<br> sed do eiusmod tempor incididunt</p>
                            </div>
                        </div>
                    </div>
                    <div class="row center">
                        <div class="col s12 m6 l3">
                            <div class="card z-depth-2 wow fadeIn" data-wow-delay="0.1s">
                                <div class="card-image waves-effect waves-block waves-light">
                                    <comentario Replace 'src' attribute with the path to the team member image  
                                    <img src="img/team/team1.png" alt="" class="trans-effect circle responsive-img">
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">Martin<i class="ion-android-more-vertical right"></i></span>
                                    <p>CEO</p>
                                    <ul class="list-inline list-follow">
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-facebook"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-twitter"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-linkedin"></i></a></li>
                                    </ul>
                                </div>
                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">Martin<i class="ion-android-close right"></i></span>
                                    <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>
                                </div>
                            </div>
                        </div>comentario Col ends    
                        <div class="col s12 m6 l3">
                            <div class="card z-depth-2 wow fadeIn" data-wow-delay="0.2s">
                                <div class="card-image waves-effect waves-block waves-light">
                                    comentario Replace 'src' attribute with the path to the team member image  
                                    <img src="img/team/team2.png" alt="" class="trans-effect circle responsive-img">
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">Peter<i class="ion-android-more-vertical right"></i></span>
                                    <p>Project manager</p>
                                    <ul class="list-inline list-follow">
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-facebook"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-twitter"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-linkedin"></i></a></li>
                                    </ul>
                                </div>
                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">Peter<i class="ion-android-close right"></i></span>
                                    <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>
                                </div>
                            </div>
                        </div>comentario Col ends    
                        <div class="col s12 m6 l3">
                            <div class="card z-depth-2 wow fadeIn" data-wow-delay="0.3s">
                                <div class="card-image waves-effect waves-block waves-light">
                                    comentario Replace 'src' attribute with the path to the team member image  
                                    <img src="img/team/team3.png" alt="" class="trans-effect circle responsive-img">
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">Sofia<i class="ion-android-more-vertical right"></i></span>
                                    <p>Developer</p>
                                    <ul class="list-inline list-follow">
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-facebook"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-twitter"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-linkedin"></i></a></li>
                                    </ul>
                                </div>
                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">Sofia<i class="ion-android-close right"></i></span>
                                    <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>
                                </div>
                            </div>
                        </div> comentario Col ends    
                        <div class="col s12 m6 l3">
                            <div class="card z-depth-2 wow fadeIn" data-wow-delay="0.4s">
                                <div class="card-image waves-effect waves-block waves-light">
                                    comentario Replace 'src' attribute with the path to the team member image  
                                    <img src="img/team/team4.png" alt="" class="trans-effect circle responsive-img">
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">Mike<i class="ion-android-more-vertical right"></i></span>
                                    <p>Designer</p>
                                    <ul class="list-inline list-follow">
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-facebook"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-twitter"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-linkedin"></i></a></li>
                                    </ul>
                                </div>
                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">Mike<i class="ion-android-close right"></i></span>
                                    <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>
                                </div>
                            </div>
                        </div>comentario Col ends   
                    </div> Row ends    
                </div> Container ends            
            </div> Sec-padded ends     
        </section> Section ends -->

        <!-- Section testimonials -->
        <section id="testimonials" class="testimonials-section">
            <div class="sec-padded-1x">
                <div class="container">
                    <div class="row btm-mrgn-0">
                        <div class="col s12 l8 offset-l2">
                            <div class="center-heading">
                                <h3>Comunidad</h3>
                                <span class="center-line red"></span>
                                <p>Observa algunos de los comentarios de nuestros clientes.</p>
                            </div>
                        </div>
                    </div>
                    <div class="row center">
                        <div class="col s12 m10 l10 offset-m1 offset-l1">
                            <div id="testimonial-slider" class="owl-carousel owl-theme">
                                <div class="item">
                                    <div class="testimonials-inner">
                                        <!-- Replace 'src' attribute with the path to the review member image  -->
                                        <img src="img/reviewers/grisi.jpg" alt="Salvador González">
                                        <div class="testimonials-box">
                                            <p>"Los departamentos de objetos perdidos son muy ineficientes. No llevan un buen control y entregan las cosas a quien sea. Eso lo sabemos todos. Lo bueno es que, gracias a la tecnología, identificar nuestros artículos es más fácil y también lo es administrarlos y poder recuperarlos a través del Smartphone o de un Sitio Web. Se trata de eficientar las cosas y les aseguro que RECUPERA lo ha conseguido"</p>
                                            <span>Salvador González Grisi - <em>Talentus.lat</em></span>
                                        </div>
                                    </div>
                                </div><!-- Item ends -->
                                <div class="item">
                                    <div class="testimonials-inner">
                                        <!-- Replace 'src' attribute with the path to the review member image  -->
                                        <img src="img/reviewers/irene.jpg" alt="">
                                        <div class="testimonials-box">
                                            <p>"Soy una buena persona y cuando encuentro algo que no es mío, siempre intento devolverlo. El problema es que, hasta ahora, resultaba casi imposible contactar al dueño con todo y que viniera su nombre en una etiqueta. Ahora, con RECUPERA es más fácil y rápido y ya van dos objetos que devuelvo y ¡hasta me han dado recompensa!"</p>
                                            <span>Irene Sotomayor - <em>Publicista</em></span>
                                        </div>
                                    </div>
                                </div><!-- Item ends -->
                                <div class="item">
                                    <div class="testimonials-inner">
                                        <!-- Replace 'src' attribute with the path to the review member image  -->
                                        <img src="img/reviewers/Daniela Cervantes.jpg" alt="">
                                        <div class="testimonials-box">
                                            <p>"Porque es más fácil recuperar un objeto si todos colaboramos a la hora de devolverlo. Yo ya he comprobado en la escuela de mis hijas, que RECUPERA funciona como una comunidad de personas en la que nos ayudamos unos a otros a devolver eficientemente lo que es de los alumnos. Ya he recuperado rápidamente algunas prendas de valor, gracias a que llevaba una Pegalina con un código QR RECUPERA y me he ahorrado dinero al ya no tener que reponerlas."</p>
                                            <span>Daniela Cervantes - <em>Mamá y empresaria</em></span>
                                        </div>
                                    </div>
                                </div><!-- Item ends -->
                            </div><!-- Slider ends -->
                        </div><!-- Col ends -->
                    </div><!-- Row ends -->
                </div><!-- Container ends -->
            </div><!-- Sec-padded ends -->
        </section><!-- Section ends -->

        <!-- Section count -->
        <!--<section id="count" class="count-section z-depth-1">
            <div class="sec-padded-3x">
                <div class="container">
                    <div class="row center">
                        <div class="col s4 m4 l4">
                            <i class="ion-ios-people"></i>
                            <h2 class="counter">5,147</h2>
                            <p>Followers</p>
                        </div>
                        <div class="col s4 m4 l4">
                            <i class="ion-ios-cloud-download-outline"></i>
                            <h2 class="counter">3,147</h2>
                            <p>Downloads</p>
                        </div>
                        <div class="col s4 m4 l4">
                            <i class="ion-ios-compose-outline"></i>
                            <h2 class="counter">10,147</h2>
                            <p>Reviews</p>
                        </div>
                    </div>
                </div> Container ends 
            </div>Sec-padded ends 
        </section> Section ends -->

        <!-- Section location -->
       <!-- <section id="location" class="location-section">
            <div class="container-fluid">
                <div class="row btm-mrgn-0">
                    <div class="col s12 m6 l6 address-block">
                        <div class="center-heading left-align">
                            <h3>Mantente en contacto</h3>
                            <span class="center-line red"></span>
                            <p>  </p>
                        </div>
                        <ul>
                            <li><p>La app te manda la ubicación donde fue escaneado tu artículo </p>
                                
                            </li>
                            <li><p>Te pueden contactar por teléfono</p></li>
                            <li><p>Cuando una persona encuentra un artículo te llegara un correo electrónico y una notificación en la app.</p></li>
                        </ul>
                        <!--<a class="modal-trigger waves-effect waves-light btn red center md-trigger" data-modal="m-contact">Contact Us</a> <a class="modal-trigger waves-effect waves-light btn red center md-trigger" data-modal="m-sub">Subscribe to our Newsletter</a>-->
                   <!-- </div>
                    <div class="col s12 m6 l6 map-block">
                        <div id="map"></div><br>
                        <h3>Google Map</h3><br>
                        <div id="googleMap" style="width:100%;height:400px;"></div><br>

                        <script>
                        function myMap() {
                        var mapProp= {
                           center:new google.maps.LatLng(51.508742,-0.120850),
                            zoom:5,
                        };
                        var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
                        }
                        </script>

                        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-8zo5s5US-30PwyZOszJHhEo9BwlZZik&callback=myMap"></script>
                    </div>
                </div> Row ends 
            </div> Container ends 
        </section> comentario Section ends -->

        <!-- Section download -->
        <!--<section id="download" class="download-section sec-padded-1x">
            <div class="container">
                <div class="row">
                    <div class="col s12 m8 l8 offset-m2 offset-l2">
                        <div class="center-heading wow fadeIn" data-wow-delay="0.1s">
                            <!-- Replace 'href' attribute with the path to download link -->
                            <!--<h3><a href="#" class="white-text"><i class="ion-android-playstore"></i>Download App</a></h3>
                        </div>
                    </div>
                </div>
            </div> Container ends 
        </section> Section ends -->

        

        <!-- Modal for video preview -->
        <div class="md-modal md-effect-1 valign-wrapper" id="m-video">
            <div class="md-content z-depth-2">
                <a class="md-close"><i class="ion-android-close"></i></a>
                <!-- Add your video iframe here -->
                <iframe src="https://player.vimeo.com/video/212436186" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
        </div><!-- Modal ends -->

        <!-- Modal for contact from -->
        <div class="md-modal md-effect-1 valign-wrapper" id="m-contact">
            <div class="md-content z-depth-2">
                <h3>Shoot Us a Message</h3>
                <a class="md-close"><i class="ion-android-close"></i></a>
                <p>We would love to hear from you. Get in touch with us now. </p>
                <div class="row">
                    <form id="contactForm" class="col s12">
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="last_name" name="fullname" type="text">
                                <label for="last_name">Last Name</label>
                            </div>
                            <div class="input-field col s12">
                                <input id="email" name="email" type="email">
                                <label for="email">Email</label>
                            </div>
                            <div class="input-field col s12">
                                <textarea id="textarea1" name="message" class="materialize-textarea"></textarea>
                                <label for="textarea1">Textarea</label>
                            </div>
                            <div class="input-field col s12">
                                <input class="waves-effect waves-light btn red center" type="submit" value="Submit" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- Modal ends -->

        <!-- Modal for subscription from -->
        <div class="md-modal md-effect-1 valign-wrapper" id="m-sub">
            <div class="md-content z-depth-2">
                <h3>Subscribe to our Newsletter</h3>
                <a class="md-close"><i class="ion-android-close"></i></a>
                <p>Subscribe to the mailing list to keep up with new features & updates from us. Don't worry... we don't like spam either.</p>
                <div class="row">
                    <form id="subscribeForm" class="col s12">
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="email-sub" name="email" type="email">
                                <label for="email-sub">Email</label>
                            </div>
                            <div class="input-field col s12">
                                <input class="waves-effect waves-light btn red center" type="submit" value="Subscribe" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- Modal ends -->


        <!-- Modal Structure -->
    
    <div id="modal_article_found" class="modal" style="max-height: 84% !important;">
    <div class="modal-content" style="padding-bottom: 4px !important;">
        <div class="row pagetitle-row" style="margin-left: 10px">
    <div class="col s12 m2 l2">
        <img src="<?php echo $this->basePath('/img/Recupera logo OK.png') ?>" alt="pegalinas"
        style="with: 45px; height: 45px;" />
        </div>
        <div class="col s12 m10 l10">
        <h4 class="center-align">Parece que encontraste un art&iacute;culo</h4>
        </div>
        </div>
        
        <p class="center-align">Envia un mensaje al dueño del art&iacute;culo para que esté enterado y pueda contactarte.</p>
        <div class="row" style="margin-top: 20px;">
            <form id="form_article_found" method="POST" action="#" class="col s12 m12 l12">

                <input type="hidden" id="id_article" name="id_article">
                <input type="hidden" id="id_code_qr" name="id_code_qr">
                <input type="hidden" id="email_owner" name="email_owner">

                <div class="row">

                    <div class="input-field col s12 m6 l6">
                        <input id="name_p" type="text" class="validate" name="name_p" data-validetta="required" data-vd-message-required="Ingresa tu nombre" />
                        <label for="name_p">Nombre</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        <input id="phone_p" type="text" class="validate" name="phone_p" data-validetta="required" data-vd-message-required="Ingresa tu teléfono" />
                        <label for="phone_p">Tel&eacute;fono</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        <input id="email_p" type="text" class="validate" name="email_p" data-validetta="required" data-vd-message-required="Ingresa tu correo electrónico" />
                        <label for="email_p">Correo Electr&oacute;nico de contacto</label>
                    </div>

                    <div id="div_phone_u"  class="input-field col s12 m6 l6 " style="display:none;">
                        <input style="color:blue" id="phone_u" type="text" class="validate" name="phone_u" placeholder="Telefono" disabled="disabled" />
                        <label for="phone_u">Tel&eacute;fono del propietario del art&iacute;culo</label>
                    </div>

                    <div id="div_rew"  class="input-field col s12 m6 l6" >
                    </div>

                    <div id="div_reward"  class="input-field col s12 m6 l6" style="display:none;">
                        <input type="text" class="validate" disabled="disabled">                        
                        <label style="color:red" id="reward">Este art&iacute;culo cuenta con recompensa</label>
                    </div>
                    
                
                    <div class="input-field col s12 m12 l12">                   
                        <textarea id="comment_p" class="materialize-textarea" name="comment_p" data-validetta="required" data-vd-message-required="Ingresa algún comentario">Hola, encontre tu artículo. Contáctame!</textarea>
                        <label for="comment_p">Comentario</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        <button type="submit" class="waves-effect waves-light btn-large teal col s12 m12 l12">
                            <!--<i class="material-icons left">send</i>--> Enviar
                        </button>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        <a href="javascript:void(0)" id="btn_close_modal_article_found" class="waves-effect waves-light btn-large red col s12">Cerrar</a>
                    </div>  

                </div>
                
            </form>
        </div>
    </div>
    <!--<div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>-->
</div>



        <!-- Scripts -->
        <script>

    // BasePath
    var $basePath           = '<?php echo $this->basePath(); ?>';

    
    // Formulario
    var $form_article       = $("#form_article");


    // FORMULARIO DE CONTACTAR AL DUENO DE UN ARTICULO
    var $form_article_found = $("#form_article_found");


    // Cuando el documento esta listo
    $(document).ready(function() {

        // BANDERA MOSTRAR MODAL
        var $flagShowModal = localStorage.getItem("flagShowModal");

        // VALIDAMOS LA VARIABLE ALMACENADA
        if ($flagShowModal != "okFlagShowModal") {

            // MOSTRAMOS ALERTA
            swal({
                imageUrl:"<?php echo $this->basePath('/img/icons/Recupera Icon - copia.png') ?> ",
                title: "¿Eres una institución?<br> (Colegio, Camp, Gym, etc) ",
                showCancelButton: true,
                //confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'SI',
                cancelButtonText: 'NO'
            }).then(function () {

                // GENERMAMOS UNA VARIABLE EN EL ALMACENAMIEENTO LOCAL
                localStorage.setItem("flagShowModal", "okFlagShowModal");

                window.location.href= '#describe';

            }, function (dismiss) {

                // GENERMAMOS UNA VARIABLE EN EL ALMACENAMIEENTO LOCAL
                localStorage.setItem("flagShowModal", "okFlagShowModal");

            });
        };

        // ******************************************************************
        // MODALES SE INICIALIZAN
        // ****************************************************************** 
        $('.modal').modal({
            dismissible: false,// Callback for Modal close
        });


        // ******************************************************************
        // CLICK EN EL BOTON CERRAR MODAL DE PIN
        // ******************************************************************
        $('#btn_close_modal_article_found').on('click', function(event) {
            event.preventDefault();
            
            // OCULTAMOS MODAL DE ENCONTRASTE UN ARTICULO
            $("#modal_article_found").modal('close');

            // LIMPIAMOS CAMPO
            $('#name_p').val('');
            // QUITAMOS FOCO AL INPUT
            $('#name_p').blur();
            // REMOVEMOS VALIDACION DEL INPUT
            $('#name_p').next().next().remove();

            // LIMPIAMOS CAMPO
            $('#phone_p').val('');
            // QUITAMOS FOCO AL INPUT
            $('#phone_p').blur();
            // REMOVEMOS VALIDACION DEL INPUT
            $('#phone_p').next().next().remove();

            // LIMPIAMOS CAMPO
            $('#email_p').val('');
            // QUITAMOS FOCO AL INPUT
            $('#email_p').blur();
            // REMOVEMOS VALIDACION DEL INPUT
            $('#email_p').next().next().remove();

            // LIMPIAMOS CAMPO
            //$('#comment_p').val('');
            // QUITAMOS FOCO AL INPUT
            //$('#comment_p').blur();
            // REMOVEMOS VALIDACION DEL INPUT
            //$('#comment_p').next().next().remove();
            
        });

        // ******************************************************************
        // VALIDAR FORMULARIO DE CONTACTAR AL DUENO DE UN ARTICULO
        // ******************************************************************
        $form_article_found.validetta({
            bubblePosition : 'bottom',
            bubbleGapTop   : 10,
            bubbleGapLeft  : 5,
            realTime : true,
            onValid  : function(event){
                event.preventDefault();

                $.ajax({
                    url      : $basePath + '/articles/codeqr',
                    type     : 'POST',
                    dataType : 'json',
                    data     : $(this.form).serialize(),
                })
                .done(function(response) {
                    console.log(JSON.stringify(response));
                    //console.log("success");

                    // Validamos la respuesta
                    if (response.status == 'ok') {

                        swal(
                            'Gracias...',
                            '¡Tu mensaje ha sido enviado!',
                            'success'
                        ).catch(swal.noop).then(function (result) {
                                
                            // OCULTAMOS MODAL DE ENCONTRASTE UN ARTICULO
                            $("#modal_article_found").modal('close');

                            // LIMPIAMOS CAMPO
                            $('#name_p').val('');
                            // QUITAMOS FOCO AL INPUT
                            $('#name_p').blur();
                            // REMOVEMOS VALIDACION DEL INPUT
                            $('#name_p').next().next().remove();

                            // LIMPIAMOS CAMPO
                            $('#phone_p').val('');
                            // QUITAMOS FOCO AL INPUT
                            $('#phone_p').blur();
                            // REMOVEMOS VALIDACION DEL INPUT
                            $('#phone_p').next().next().remove();

                            // LIMPIAMOS CAMPO
                            $('#email_p').val('');
                            // QUITAMOS FOCO AL INPUT
                            $('#email_p').blur();
                            // REMOVEMOS VALIDACION DEL INPUT
                            $('#email_p').next().next().remove();

                        });
                       
                    } else {
                        swal(
                            'Opsss..',
                            '¡Ocurrio un error, intentalo de nuevo!',
                            'error'
                        ).catch(swal.noop);
                    }

                })
                .fail(function() {
                    console.log("error");
                })
                .always(function() {
                    console.log("complete");
                });
            }
        });

        // ******************************************************************
        // VALIDAR FORMULARIO DEL CODIGO QR
        // ******************************************************************
        $form_article.validetta({
            bubblePosition: 'bottom',
            bubbleGapTop: 10,
            bubbleGapLeft: 0,
            realTime : true,
            onValid : function( event ) {
                event.preventDefault();

                $.ajax({
                    url: $basePath + '/articles/validatecodeqr',
                    type: 'POST',
                    dataType: 'json',
                    data: $(this.form).serialize(),
                })
                .done(function(response) {
                    //console.log(JSON.stringify(response));

                    // YA ESTA ASIGNADO A ALGUN ARTICULO
                    // {"data":[{"count":"1","id":"1","id_status":"7","id_article":"14","name_article":"39"}]}

                    // NO ESTA ASIGNADO A NINGUN ARTICULO
                    // {"data":[{"count":"1","id":"3","id_status":"1","id_article":"-1","name_article":null}]}

                    //console.log("success");
                    // VALIDAMOS SI EL CODIGO EXISTE
                    if (response.data[0]['count'] == 1) {

                        // VALIDAMOS EL ESTATUS Y EL ID DEL ARTICULO
                        //if (response.data[0].id_status == 1 && response.data[0].id_article == -1) {
                            
                            /**swal(
                                'Opsss..',
                                '¡El código ingresado no esta asignado a algún artículo',
                                'warning'
                            );*/

                        //} else {

                            // AGREGAMOS UN VALOR AL INPUT email_owner
                            /*$("#email_owner").val(response.data[0].email_owner);

                            // AGREGAMOS UN VALOR AL INPUT id_article
                            $("#id_article").val(response.data[0].id_article);

                            // AGREGAMOS UN VALOR AL INPUT id_code_qr
                            $("#id_code_qr").val(response.data[0].id);

                            if (response.data[0].reward != 0 && response.data[0].reward != "") { 

                                $('#div_reward').show();
                            
                                // MOSTRAR MODAL si tiene recompensa
                                $('#reward').val(response.data[0].reward);
                            }
                            if (response.data[0].phone != "") { 

                                $('#div_phone_u').show();
                            
                                // MOSTRAR MODAL si tiene recompensa
                                $('#phone_u').val(response.data[0].phone_users);

                                $("#phone_u").focus();
                            }*/

                            // MOSTRAR MODAL PARA CONTACTAR AL DUENO
                            //$('#modal_article_found').modal('open');

                            if(response.data[0].type_qr == 1){

                                window.location.href = $basePath + '/articles/codeqr/' + $("#code_article").val();

                            } else if(response.data[0].type_qr == 2) {

                                //ruta para servidor de produccion
                                //window.location.href = 'https://recupera.pet/pets/codeqr/' + $("#code_article").val();

                                window.location.href = $basePath + '/pets/codeqr/' + $("#code_article").val();

                            };
                            

                        //} 

                    } else if(response.data[0]['count'] == 0) {
                        swal(
                            'Opsss..',
                            '¡El código ingresado no es valido!',
                            'error'
                        );
                    }

                })
                .fail(function() {
                    console.log("error");
                })
                .always(function() {
                    console.log("complete");
                });
            }
        });

    });

</script>
        <!--<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>-->
       
        <script src="<?php echo $this->basePath('/js/materialize.min.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/jquery.smoothscroll.min.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/typed.min.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/wow.min.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/waypoint.min..js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/jquery.counterup.min.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/owl.carousel.min.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/jquery.flexslider-min.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/jquery.validate.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/classie.js" type="text/javascript');?>"></script>
        <script src="<?php echo $this->basePath('/js/config.js" type="text/javascript');?>"></script>
       


    </body>

</html>
