<br><br><br><br><br><!--Import Google Icon Font-->
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath('pegalinaslive/materialize/css/materialize.min.css'); ?>"  media="screen,projection"/>

        <link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Roboto&subset=latin,devanagari" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath('/pegalinaslive/sweetalert2/sweetalert2.min.css'); ?>" />
        <link href="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.css'); ?>" rel="stylesheet" type="text/css" media="screen" >




 <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('pegalinaslive/materialize/js/materialize.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/sweetalert2/sweetalert2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/localization/validettaLang-es-ES.js'); ?>"></script>

        <style>
.circle-icon .material-icons {
  position: absolute;
  margin-top: -58px;
  margin-left: -46px;
  background-color: #009688;
  color: white;
  padding: 8px;
  font-size: 3em;
  /*border-radius: 50%; */
  transform: rotate(15deg);
}
</style>

  <div class="col s12 m6 offset-m3 l4 offset-l4">


    <div class="card">
      <div class="card-content">
        <form id="form_validate_change_pass">
          <div class="row">
            <div class="col s12 m12 l12 center">
                <img class="responsive-img" src="<?php echo $this->basePath('/img/Recupera by 667x152px.png') ?>" alt="logo-pegalinas">
            </div>
          </div>
          <div class="row">
            <div class="col s12 m12 l12">
              <p class="center-align grey-text text-darken-3">Has solicitado un cambio de contrase&ntilde;a. Ingresa una nueva contrase&ntilde;a para iniciar sesión con tu cuenta.</p>
            </div>
          </div>
          
            

              <input type="text" id="value_id_user" style="display:none;" name="value_id_user">

              <input type="text" id="value_token" style="display:none;" name="value_token">

                             <div id="div_update_pass" class="row">
                                <div class="col s12 m6 l6 offset-m3 offset-l3">
                                    <div class="input-field col s12 m12 l12">
                                        <input id="change_pass" type="password" name="change_pass" class="validate" data-validetta="required" data-vd-message-required="Ingresa la contrase&ntilde;a">
                                        <label for="password1">Nueva Contrase&ntilde;a</label>
                                    </div>

                                    <div class="input-field col s12 m12 l12">
                                        <input id="change_pass2" type="password" name="change_pass2" class="validate" data-validetta="required" data-vd-message-required="Ingresa la contrase&ntilde;a">
                                        <label for="password2">Repite Contrase&ntilde;a</label>
                                    </div>
                                </div>

                                 <div class="col s12 m6 l6 offset-m3 offset-l3">
                                
                                <div class="col s12 m6 l6">
                                    <button type="submit" id="btn_validate_pass" class="waves-effect waves-green btn-large teal col s12">
                                    Aceptar
                                    </button>
                                </div>

                                <div class="col s12 m6 l6">
                                    <a href="javascript:void(0)" class="modal-action modal-close waves-effect waves-green btn-large red col s12">Cerrar</a>
                                </div>
                                
                            </div>
                                
                            </div>
          </form>
          </div>
          
        
      </div>
    </div>

  </div>
</div>


<script>
  // BasePath
  var $basePath = '<?php echo $this->basePath(); ?>';

  var $id_user  = "<?php echo $this->id_user; ?>";

  var $token  = "<?php echo $this->token; ?>";

  // FORMULARIO contraseña sesion 
            $form_validate_change_pass = $("#form_validate_change_pass");

            $(document).ready(function(){

              $('#value_id_user').val($id_user);

              $('#value_token').val($token);

              $form_validate_change_pass.validetta({
               bubblePosition: 'bottom',
              bubbleGapTop: 10,
              bubbleGapLeft: 0,
              realTime : true,
              onValid : function( event ) {

        event.preventDefault();

        // Validamos si los codigos qr son correctos
        if ($('#change_pass').val() != $("#change_pass2").val()) {
          // Mostramos alerta
          swal(
              'Atención',
              '¡Las contraseñas no coinciden!',
              'error'
          );
            
        } else {

              $.ajax({
                url: $basePath + '/auth/passwordrecovery',
                type: 'POST',
                dataType: 'json',
                data: $(this.form).serialize(),
              })
              .done(function(response) {
                console.log(response);
                //console.log("success");
                if (response.status == 'ok') {
                  window.location = $basePath + '/auth';
                } else if(response.status == 'fail'){
                  swal(
                  'Opsss..',
                  '¡Ocurrio un error intentalo de nuevo!',
                  'error'
              );
                }

              })
              .fail(function() {
                console.log("error");
              })
              .always(function() {
                console.log("complete");
              });

            }


          }
  });

});




</script>
