<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icons/favicons/icono app.ico')); ?>

    <title>Recupera</title>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="<?php echo $this->basePath('css/ionicons.min.css" rel="stylesheet');?>" type="text/css"/>

    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath("pegalinaslive/materialize/css/materialize.min.css"); ?>"  media="screen,projection"/>

    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath("pegalinaslive/css/style-pegalinas.css"); ?>" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath('/pegalinaslive/sweetalert2/sweetalert2.min.css'); ?>" />
    <link href="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.css'); ?>" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"/>

    <!--Import jQuery before materialize.js-->
    
    <script type="text/javascript" src="<?php echo $this->basePath("pegalinaslive/jquery/jquery-2.2.4.min.js"); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath("pegalinaslive/materialize/js/materialize.min.js"); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/sweetalert2/sweetalert2.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/localization/validettaLang-es-ES.js'); ?>"></script>
<style>
.pets i {
    color: #FF1E73;
}

</style>

</head>
<body>

    <header>
        
        <div class="navbar-fixed">
            <nav class="white">
                <div class="nav-wrapper container">
                    <a href="javascript:void(0);" class="brand-logo">
                        <img src="<?php echo $this->basePath('img/Recupera by 667x152px.png'); ?>" alt="logo recupera" />
                    </a>
                    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                    <ul class="right hide-on-med-and-down">
                        <li>
                            <a data-keysecure="perfil" class="btn_validate_articles" href="<?php echo $this->basePath('/users/perfil'); ?>"><i class="material-icons left">account_circle</i>Mi Perfil</a>
                        </li>
                        <li>
                            <a data-keysecure="articles" class="btn_validate_articles" href="javascript:void(0);"><i class="material-icons left">list</i>Art&iacute;culos</a>
                        </li>
                        <!--<li class="item_pet">
                            <a data-keysecure="pets" class="btn_validate_articles pets" href="javascript:void(0);"><i class="material-icons left">pets</i>Mascotas</a>
                        </li>-->
                        <li>
                            <a href="<?php echo $this->basePath('/auth/logout'); ?>"><i class="material-icons left">power_settings_new</i>Salir</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

        <ul class="side-nav" id="mobile-demo">
            <li><a data-keysecure="perfil" class="btn_validate_articles" href="<?php echo $this->basePath('/users/perfil'); ?>"><i class="material-icons left">account_circle</i>Mi Perfil</a></li>
            <li><a data-keysecure="articles" class="btn_validate_articles" href="javascript:void(0);"><i class="material-icons left">list</i>Art&iacute;culos</a></li>
            <!--<li class="item_pet"><a data-keysecure="pets" class="btn_validate_articles" href="javascript:void(0);"><i class="material-icons left">pets</i>Mascotas</a></li>-->
            <li><a href="<?php echo $this->basePath('/auth/logout'); ?>"><i class="material-icons left">power_settings_new</i>Salir</a></li>
        </ul>
    
    </header>

    <main>
        <div class="container" style="margin-top: 20px; margin-bottom: 60px;">

            <?php echo $this->content; ?> 

        </div>
    </main>

    <footer id="footer" class="footer-main">
        <div class="container">
            <div class="row">

                <div class="col s12 m8 l8 offset-m2 offset-l2 center">

                    <a href="javascript:void(0);">
                        <img src="<?php echo $this->basePath('img/icons/Recupera By.png'); ?>" alt="logo recupera">
                    </a>

                    <div class="clearfix"></div>

                    <ul class="list-inline footer-social">
                        <li>
                            <a href="https://www.facebook.com/RecuperaMx/" target="_blank"><i class="ion-social-facebook waves-effect waves-light"></i></a>
                        </li>
                        <li>
                            <a href="https://twitter.com/pegalinas" target="_blank"><i class="ion-social-twitter waves-effect waves-light"></i></a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/channel/UCnzEiknp5FrTbw3zAUaNpjg" target="_blank"><i class="ion-social-youtube waves-effect waves-light"></i></a>
                        </li>
                    </ul>

                    <hr>

                    <span class="copyrights">&copy; Recupera, Todos los derechos reservados 
                        <a class="_m4qul" href="<?php echo $this->basePath('/Documents/Política de privacidad Recupera.net.pdf')?>" target="_blank">Política de privacidad</a>
                        y
                        <a  href="<?php echo $this->basePath('/Documents/Aviso Legal y Cond de uso Recupera.net.pdf')?>" target="_blank">Condiciones</a>
                    </span>

                </div>

            </div>
        </div>
    </footer>
    <div style="background-color: #263238;">
      <div class="container">
           <div class="row" style="margin-bottom: 0;">
              <center>
                   <div class="col s12 m12 l12">
                   <!-- webbot  bot="HTMLMarkup" startspan -->
                   <!-- GeoTrust QuickSSL [tm] Smart  Icon tag. Do not edit. -->
                   <script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
                   <!-- end  GeoTrust Smart Icon tag -->
                   <!-- webbot  bot="HTMLMarkup" endspan -->
                    </div>
              </center>
            </div>
      </div>
    </div>

    <!-- Modal Structure -->
    <div id="modal_validate_articles" class="modal">
        <div class="modal-content">

            <div class="row pagetitle-row" style="margin-left: 10px">
                <div class="col s2">
                    <img src="<?php echo $this->basePath('/img/Recupera logo OK.png') ?>" alt="pegalinas" style="with: 45px; height: 45px;" />
                </div>
                <div class="col s8">
                    <h4 class="center-align">Contrase&ntilde;a de seguridad</h4>
                </div>
        
            </div>

            <p class="center-align">Para ingresar a esta secci&oacute;n debes ingresar tu Contrase&ntilde;a de seguridad</p>
            <p class="center-align">Durante tu sesi&oacute;n no tendras que volverla a escribir.</p>
                
            <div class="row" style="margin-top: 20px;">
                <div class="col s12 m12 l12">
                    <form id="form_validate_articles">
              
                        <div class="row" style="margin-bottom: 0;">
                            <div class="col s12 m6 l6 offset-m3 offset-l3">
                                <div class="input-field col s12 m12 l12">
                                    <input id="key_inventory" type="password" name="password_articles" class="validate" data-validetta="required" data-vd-message-required="Ingresa la contrase&ntilde;a">
                                    <label for="key_inventory">Contrase&ntilde;a</label>
                                </div>
                            </div>                                    
                        </div>

                        <div class="row">
                            <div class="col s12 m12 l12">
                                <p class="btn_forgot_pass center" style="font-size:15px; margin-top: 0;">
                                    <a href="javascript:void(0)">¿Olvidaste tu contrase&ntilde;a de seguridad?</a>
                                </p>
                            </div>
                        </div>

                        <div class="col s12 m6 l6 offset-m3 offset-l3">
                            <div class="col s12 m6 l6">
                                <button type="submit" id="btn_validate_pass_articles" class="waves-effect waves-green btn-large teal col s12">
                                    Aceptar
                                </button>
                            </div>

                            <div class="col s12 m6 l6">
                                <a href="javascript:void(0)" class="modal-action modal-close waves-effect waves-green btn-large red col s12">Cerrar</a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

        </div>
        <!--<div class="modal-footer">      
        </div>-->
    </div>

    <script>

    // RUTA BASE DEL PROYECTO
    var $basePath               = '<?php echo $this->basePath(); ?>';
    
    var $btn_forgot_pass        = $('.btn_forgot_pass'); //para recuperar contraseña de inventario
    
    // FORMULARIO
    var $form_validate_articles = $("#form_validate_articles");
    
    // Boton de clave se seguridad
    var $btn_validate_articles  = $('.btn_validate_articles');

    var $data_keysecure         = "";

    var $type_user              = localStorage.getItem("type_user");

    // VALIDAR TIPO DE CUENTA PARA MOSTRAR O NO OPCION DE MASCOTAS
    if($type_user=="institucion") {
        $(".item_pet").hide();
    } else if($type_user=="personal") {
        $(".item_pet").show();
    };
    
    // ***************************************************************
    // CARGA DEL DOCUMENTO
    // ***************************************************************
    $(document).ready(function() {

        // ***************************************************************
        // INICIARLIZAR MODALES
        // ***************************************************************
        $('.modal').modal({
            dismissible: false
        });

        // ***************************************************************
        // INICIARLIZAR MENU DESPLEGABLE
        // ***************************************************************
        $(".button-collapse").sideNav();

        // ***************************************************************
        // CLICK EN EL BOTON VALIDAR ARTICULOS
        // ***************************************************************
        $btn_validate_articles.on('click', function(event) {
            
            event.preventDefault();

            // Atributo data-keysecure
            $data_keysecure = $(this).data('keysecure');

            console.log("data-keysecure: " + $data_keysecure);
            
            // Llamanos a la funcion validar clave de seguridad
            validateKeySecure($data_keysecure);

        });

        // ***************************************************************
        // VALIDAR FORMULARIO
        // ***************************************************************
        $form_validate_articles.validetta({
            bubblePosition: 'bottom',
            bubbleGapTop: 10,
            bubbleGapLeft: 0,
            realTime : true,
            onValid : function( event ) {

                event.preventDefault();

                //console.log("$data_keysecure: " + $data_keysecure);

                $.ajax({
                    url: $basePath + '/articles',
                    type: 'POST',
                    dataType: 'json',
                    data: $(this.form).serialize(),
                })
                .done(function(response) {
                    //console.log(response.data[0].count);
                    // Validamos la respuesta
                    if (response.data[0].count == 1) {
                        
                        // Validamos de que donde se hace la peticion
                        redirectPageR($data_keysecure);

                    } else if(response.data[0].count == 0){
                        swal(
                            'Opsss..',
                            '¡La contraseña no es correcta!',
                            'error'
                        ).catch(swal.noop);
                    }

                })
                .fail(function() {
                    console.log("error");
                })
                .always(function() {
                    console.log("complete");
                });

            }
        });

        // ***************************************************************
        // CLICK EN olvide contraseña para recuperala
        // ***************************************************************
        $btn_forgot_pass.on('click', function(event) {
            //event.preventDefault();
                    
            // Llamanos a la funcion validar articulos
            forgotPass();

        });        
        
    });

    // ***************************************************************
    // FUNCION PARA VALIDAR LISTA DE ARTICULOS
    // ***************************************************************
    function forgotPass()
    {

        // MOSTRAMOS ALERTA
        swal({
            imageUrl:"<?php echo $this->basePath('/img/email.png') ?> ",
            title: "Te enviaremos un correo electrónico a tu cuenta para que recuperes la contraseña",
            showCancelButton: true,
            //confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'SI',
            cancelButtonText: 'NO'
        }).then(function () {

                $.ajax({
                            url: $basePath + '/users/restorkeyinvento',
                            type: 'POST',
                            dataType: 'json',
                            data: $(this.form).serialize(),
                            //alert("option");
                        })
                        .done(function(response) {

                            console.log(response);
                            console.log("success");
                            if (response.status == 'ok') {
                                
                                swal({
                                    title:'Verifica tu correo electrónico',                                 
                                    imageUrl:"<?php echo $this->basePath('/img/email.png') ?>",
                                    
                                    html:'<p>¡Hemos atendido tu solicitud, por favor verifica la bandeja de entrada dónde se te envió una nueva clave de seguridad generada por recupera.!',
                                    confirmButtonText: 'Aceptar'
                                                                    
                                }).then(function () {
                                 window.location.href = $basePath + '/users/perfil';
                                 });

                            } else if (response.status == 'fail') {

                                swal(
                                    'Opsss..',
                                    '¡Correo electrónico no registrado en Recupera by Pegalinas!',
                                    'error'
                                );

                                //grecaptcha.reset();

                            }

                        })
                        .fail(function() {
                            console.log("error");
                        })
                        .always(function() {
                            console.log("complete");
                        });

        }, function (dismiss) {

            // GENERMAMOS UNA VARIABLE EN EL ALMACENAMIEENTO LOCAL
            //localStorage.setItem("flagShowModal", "okFlagShowModal");

        });
                             
    }

    // ***************************************************************
    // FUNCION PARA VALIDAR CONTRASENA DE SEGURIDAD
    // ***************************************************************
    function validateKeySecure($data_keysecure)
    {

        $.ajax({
            url: $basePath + '/articles/statuskeyinventoryandperfil',
            type: 'POST',
            dataType: 'json',
        })
        .done(function(response) {
            //console.log(JSON.stringify(response));

            // Validamos el tipo de usuario (Persona)
            if (response.perfil_user == 1) {
                 
                // Validamos de que donde se hace la peticion
                redirectPageR($data_keysecure);

            } else if (response.perfil_user == 2) { // (Institucion)

                // Validamos la respuesta
                if (response.status_key == 8102) {

                    // Validamos de que donde se hace la peticion
                    redirectPageR($data_keysecure);

                } else {

                    // MOSTRAMOS LA VENTANA MODAL
                    $('#modal_validate_articles').modal('open');

                }

            }
                        
        })
        .fail(function() {
            console.log("error");
        })
        .always(function() {
            console.log("complete");
        });
                             
    }

    // ***************************************************************
    // FUNCION PARA REDIRIGIR
    // ***************************************************************
    function redirectPageR($data_keysecure)
    {
        // Validamos de que donde se hace la peticion
        switch($data_keysecure) {
            case "perfil" :
                // Redirigimos a perfil
                window.location = $basePath + '/users/perfil';
                break;
            case "articles" :
                // Redirigimos a articulos
                window.location = $basePath + '/articles';
                break;
            case "pets" :
                // Redirigimos a mascotas
                window.location = $basePath + '/pets';
                break;
        };

    }

    </script>
    
</body>
</html>